base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('posts/', views.posts, name='posts'),
    path('post/<slug:slug>', views.post, name='post'),
    path('profile/', views.profile, name='profile'),
    #CRUD paths
    path('create_post/', views.createPost, name='create_post'),
    path('update_post/<slug:slug>', views.updatePost, name='update_post'),
    path('delete_post/<slug:slug>', views.deletePost, name='delete_post'),
    path('send_email/', views.sendEmail, name='send_email'),
]

portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) \
  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

base/models.py
from django.db import models
from django.utils.text import slugify
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField


class Tag(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Post(models.Model):
    headline = models.CharField(max_length=200)
    subheadline = models.CharField(max_length=200, null=True, blank=True)
    thumbnail = models.ImageField(null=True, blank=True, upload_to="images", default="/images/placeholder.png")
    body = RichTextUploadingField(null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)
    featured = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, null=True)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.headline
    
    def save(self, *args, **kwargs):
        if self.slug is None:
            slug = slugify(self.headline)
            #
            # self.slug = slug
            has_slug = Post.objects.filter(slug=slug).exists()
            count = 1
            while has_slug:
                count += 1
                slug = slugify(self.headline) + '-' + str(count)
                has_slug = Post.objects.filter(slug=slug).exists()
            self.slug = slug
        super().save(*args, **kwargs)

base/forms.py
from django import forms
from django.forms import ModelForm

from .models import Post


class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = '__all__'

        widgets = {
            'tags': forms.CheckboxSelectMultiple(),
        }

base/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import HttpResponse

from django.core.mail import EmailMessage
from django.conf import settings
from django.template.loader import render_to_string

from .models import Post
from .forms import PostForm
from .filters import PostFilter


def home(request):
    # only get the first 3 posts for index.html
    posts = Post.objects.filter(active=True, featured=True)[0:3]
    context = {'posts': posts}
    return render(request, 'index.html', context)


def post(request, slug):
    post = Post.objects.get(slug=slug)
    context = {'post': post}
    return render(request, 'post.html', context)


def posts(request):
    posts = Post.objects.filter(active=True)
    filter = PostFilter(request.GET, queryset=posts)
    posts = filter.qs

    page = request.GET.get('page')
    paginator = Paginator(posts, 3)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    context = {'posts': posts, 'myFilter': filter}
    return render(request, 'posts.html', context)


def profile(request):
    return render(request, 'profile.html')


# CRUD Views
@login_required(login_url='home')
def createPost(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
        return redirect('posts')
    context = {'form': form}
    return render(request, 'post_form.html', context)


@login_required(login_url='home')
def updatePost(request, slug):
    post = Post.objects.get(slug=slug)
    form = PostForm(instance=post)

    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form.save()
        return redirect('posts')
    context = {'form': form}
    return render(request, 'post_form.html', context)


@login_required(login_url='home')
def deletePost(request, slug):
    post = Post.objects.get(slug=slug)
    if request.method == 'POST':
        post.delete()
        return redirect('posts')
    context = {'post': post}
    return render(request, 'delete.html', context)


def sendEmail(request):
    if request.method == 'POST':
        template = render_to_string('email_template.html', {
            'name': request.POST['name'],
            'email': request.POST['email'],
            'message': request.POST['message'],
        })
        email = EmailMessage(
            request.POST['subject'],
            template,
            settings.EMAIL_HOST_USER,
            ['sebastian.kuppa@web.de'],
        )
        email.fail_silently = False
        email.send()

    return render(request, 'email_sent.html')

base/templates/delete.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<div class="main-container">
    <form method="POST" action="">
        {% csrf_token %}
        <p>Are you sure you want to delete post: {{post.headline}} ?</p>
        <input class="btn btn-danger" type="submit" value="Confirm">
    </form>
</div>

{% endblock content %}

base/templates/email_sent.html
{% extends 'main.html' %}

{% block content %}
<style type="text/css">
    html, body{
        height: 100%;
    }
    #page-wrapper{
        height: 100%;
        display: flex;
        justify-content: center;
        align-items: center;
        text-align: center;
        background-color: #eaeaea;
    }
</style>
<div id="page-wrapper">
    <div id="success-box" class="content-block">
        <h1>Thanks for reaching out!</h1>
        <p>Your message was successfully sent. I will do my best to get back to you
        in a timely manner :)</p>
        <a id="back-btn" href="{% url 'home' %}" class="btn btn-dark">BACK TO HOME PAGE</a>
    </div>
</div>
{% endblock content %}

base/templates/email_template.html
{{message}}
{{name}}
{{email}}

base/templates/index.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Sebastian Kuppa</title>


	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
	<link id="theme-style" rel="stylesheet" type="text/css" href="">
</head>
<body>

	<section class="s1">
		<div class="main-container">
			<div class="greeting-wrapper">
				<h1>Hi, I'm Sebastian Kuppa</h1>
			</div>


			<div class="intro-wrapper">
				{% include 'navbar.html' %}

				<div class="left-column">
					<img id="profile_pic" src="{% static 'images/Sebastian.jpg' %}">
					<h5 style="text-align: center;line-height: 0;">Personalize Theme</h5>

					<div id="theme-options-wrapper">
						<div data-mode="light" id="light-mode" class="theme-dot"></div>
						<div data-mode="blue" id="blue-mode" class="theme-dot"></div>
						<div data-mode="green" id="green-mode" class="theme-dot"></div>
						<div data-mode="purple" id="purple-mode" class="theme-dot"></div>
					</div>

					<p id="settings-note">*Theme settings will be saved for<br>your next visit</p>
				</div>

				<div class="right-column">

					<div id="preview-shadow">
						<div id="preview">
							<div id="corner-tl" class="corner"></div>
							<div id="corner-tr" class="corner"></div>
							<h3>Software Engineer with a focus on Machine Learning and Robotics based in Germany.</h3>
							<!-- <p>
							   As a software engineer, I am passionate about developing innovative solutions to complex
							   problems. I have experience with a variety of programming languages and technologies,
							   including Python, GIT, and Linux. I am a dedicated and detail-oriented team player with
							   strong problem-solving and analytical skills.
							</p> -->
							<div id="corner-br" class="corner"></div>
							<div id="corner-bl" class="corner"></div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class="s2">
		<div class="main-container">

			<div class="about-wrapper">
				<div class="about-me">
					<h4>More about me</h4>

					<p>As a software engineer, I am passionate about developing innovative solutions to complex
							   problems. I have experience with a variety of programming languages and technologies,
							   including Python, GIT, and Linux. I am a dedicated and detail-oriented team player with
							   strong problem-solving and analytical skills.</p>

					<!-- <p>While I keep busy teaching courses, I still take interviews in search of a great team & projects that interest me.</p>
					-->

					<hr>

					<h4>TOP EXPERTISE</h4>

					<p>Data Engineer with Experience in Machine Learning and Robotics:
						<br>
						<a target="_blank" href="{% static 'CV_Kuppa_2023_eng.pdf' %}">Download Resume (ENGLISH)</a>
						<br>
						<a target="_blank" href="{% static 'CV_Kuppa_2023_deutsch.pdf' %}">Download Resume (DEUTSCH)</a>
						<br>
					</p>

					<div id="skills">
						<ul>
							<li>Python</li>
							<li>Pytorch, Tensorflow</li>
							<li>Robot Operating System</li>
							<li>Django</li>
							<li>JavaScript</li>
						</ul>

						<ul>
							<li>GitLab API</li>
							<li>Numpy,Pandas,SciPy</li>
							<li>OpenCV</li>
							<li>Heroku</li>
							<li>HTML/CSS</li>
						</ul>

					</div>

				</div>

				
				<div class="social-links">
					<!-- <img id="social_img" src="{{ STATIC_URL }}images/follow.jpg"> -->

					<h3>Find me on GitHub</h3>

					<a target="_blank" href="https://github.com/SebastianKuppa">Github: @SebastianKuppa</a>

					<h3>Find me on LinkedIn</h3>

					<a target="_blank" href="https://www.linkedin.com/in/sebastian-kuppa-946909161/">LinkedIn: @SebastianKuppa</a>
				</div>
			</div>

		</div>
	</section>

	<section class="s1">
		<div class="main-container">
			<h3 style="text-align: center;">Some of my past projects</h3>

			<div class="post-wrapper">
				{% for post in posts %}
				<div>
					<div class="post">
						<a href="{% url 'post' post.slug %}"><img class="thumbnail" src={{post.thumbnail.url}}></a>
						<div class="post-preview">
							<h6 class="post-title">{{post.headline}}</h6>
							<p class="post-intro">{{post.subheadline}}</p>
							<a href="{% url 'post' post.slug %}">Read More</a>
						</div>
					</div>
				</div>
				{% endfor %}

			</div>

			<p align="center">
				<a href="{% url 'posts' %}">View More</a>
			</p>
		</div>
	</section>

	<section class="s2">
		<div class="main-container">
			<a href=""></a>
			<h3 style="text-align: center;">Get In Touch</h3>

			<form id="contact-form" method="POST" action="{% url 'send_email' %}">
				{% csrf_token %}
				<a name="contact"></a>

				<label>Name</label>
				<input class="input-field" type="text" name="name">

				<label>Subject</label>
				<input class="input-field" type="text" name="subject">

				<label>Email</label>
				<input class="input-field" type="text" name="email">

				<label>Message</label>
				<textarea class="input-field" name="message"></textarea>

				<input id="submit-btn" type="submit" value="Send">
			</form>
		</div>
	</section> 
	<script type="text/javascript">
		let static = "{% static 'css' %}"
	</script>
	<script type="text/javascript" src="{% static 'js/script.js' %}"></script>
</body>
</html>

base/templates/main.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <title>Sebastian Kuppa</title>

	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1" />

	<link href="https://fonts.googleapis.com/css2?family=Russo+One&display=swap" rel="stylesheet">

	<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@500&family=Russo+One&display=swap" rel="stylesheet">

	<link rel="stylesheet" type="text/css" href="{% static 'css/default.css' %}">
	<link id="theme-style" rel="stylesheet" type="text/css" href="">
</head>
<body>
  {% include 'navbar.html' %}

  {% block content %}
  <!-- Here goes the content from the children like post/posts -->
  {% endblock content %}

</body>
</html>

base/templates/navbar.html
<div class="nav-wrapper">
    <!-- Link around dots-wrapper added after tutorial video -->
    <a href="{% url 'home' %}">
        <div class="dots-wrapper">
            <div id="dot-1" class="browser-dot"></div>
            <div id="dot-2" class="browser-dot"></div>
            <div id="dot-3" class="browser-dot"></div>
        </div>
    </a>


    <ul id="navigation">
        <li><a href="{% url 'home' %}#contact">Contact</a></li>
        {% if request.user.is_authenticated %}
            <li><a href="{% url 'create_post' %}">Create Post</a></li>
        {% endif %}
    </ul>
</div>

base/templates/post.html
{% extends 'main.html' %}
{% load static %}
{% block content %}

<style>
	img{
		max-width:100%;
		object-fit:cover;
	}
</style>

<div class="main-container">
	<img src="{{post.thumbnail.url}}">
	<h1>{{post.headline}}</h1>
	<h4>{{post.subheadline}}</h4>
	<p>
		{{post.body|safe}}
	</p>
</div>

{% endblock content %}

base/templates/post_form.html
{% extends 'main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<style type="text/css">
  #div_id_tags > div{
    max-height: 100px;
    overflow-y: scroll;
    border: 1px solid #888;
    padding: 5px;
    border-radius: 5px;
  }
</style>

<div class="main-container">
  <h3>Post form</h3>
  <form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {{form|crispy}}
    <input class="btn btn-primary" type="submit" value="Submit Post">
  </form>
</div>

{% endblock content %}

base/templates/posts.html
{% extends 'main.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<style type="text/css">
    #id_tags{
        overflow-y: scroll;
        max-height: 100px;
        border-radius: 5px;
        padding: 5px;
    }
    ul.pagination {
        display: inline-block;
        padding: 0;
        margin: 0;
    }

    ul.pagination li {display: inline;}
    ul.pagination li a:hover:not(.active) {background-color: #ddd;}

    ul.pagination li a {
        border-radius: 5px;
        transition: background-color .3s;
        border: 1px solid #ddd; /* Gray */
        color: black;
        float: left;
        padding: 8px 16px;
        text-decoration: none;
    }

    ul.pagination li a.active {
        background-color: #4CAF50;
        color: white;
    }
</style>

<div class="main-container">
    <h1>Posts</h1>

    <!-- <form method="GET">
        {{myFilter.form|crispy}}
        <input class="btn btn-primary" type="submit" value="search">
    </form> -->

    <div class="post-wrapper">
        {% for post in posts %}
        <div>
            <div class="post">
                <a href="{% url 'post' post.slug %}"><img class="thumbnail" src={{post.thumbnail.url}}></a>

                <div class="post-preview">
                    <h6 class="post-title">{{post.headline}}</h6>
                    <p class="post-intro">{{post.subheadline}}</p>
                    <a href="{% url 'post' post.slug %}">Read More</a>
                    {% if request.user.is_authenticated %}
                        | <a href="{% url 'update_post'  post.slug %}">Edit</a>
                        | <a href="{% url 'delete_post'  post.slug %}">Delete</a>
                    {% endif %}
                    <hr>
                    {% for tag in post.tags.all %}
                        <span class="tag">{{tag}}</span>
                    {% endfor %}
                </div>

            </div>
        </div>
        {% empty %}
            <h3>No Posts found...</h3>
        {% endfor %}
    </div>

    <div class="pagination">
        {% if posts.has_other_pages %}
            <ul class="pagination">
                {% if posts.has_previous %}
                    <li class="page-item"><a href="?page={{posts.previous_page_number}}" class="page-link">&laquo</a></li>
                    <li class="page-item"><a href="?page=1" class="page-link">First</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" style="color:rgb(211,211,211)" >&laquo</a></li>
                    <li class="page-item"><a class="page-link" style="color:rgb(211,211,211)" >First</a></li>
                {% endif %}

                {% for i in posts.paginator.page_range %}
                    {% if posts.number == i %}
                        <li class="page-item"><a class="active page-link">{{i}}</a></li>
                    {% else %}
                        <li class="page-item"><a href="?page={{i}}" class="page-link">{{i}}</a></li>
                    {% endif %}
                {% endfor %}

                {% if posts.has_next %}
                    <li class="page-item"><a href="?page={{posts.paginator.num_pages}}" class="page-link">Last</a></li>
                    <li class="page-item"><a href="?page={{posts.next_page_number}}" class="page-link">&raquo</a></li>
                {% else %}
                    <li class="page-item"><a class="page-link" style="color:rgb(211,211,211)">Last</a></li>
                    <li class="page-item"><a class="page-link" style="color:rgb(211,211,211)">&raquo</a></li>
                {% endif %}
            </ul>
        {% endif %}
    </div>



</div>

{% endblock content %}

base/templates/profile.html
{% extends 'main.html' %}
{% block content %}
    <h2>PROFILE TEMPLATE</h2>
{% endblock content %}